### ISSUE TITLE
Switch to using new EDS cdn

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1567]
**Because the old cdn will be taken off the air, we need to switch to the new one**

## Sub-tasks
- [x] Replace old url with new, cdn.eds.equinor.com
- [x] Verify that it works in dev
- [ ] Finally push to production and monitor for some time
- [ ] Report back to EDS team when fully implemented
- [x] Create issue with radix team to update the error page.

**Comment by nilsml** [comment]
This one is quite urgent as the old cdn will be taken off air pretty soon.
@fernandolucchesi

**Comment by padms** [comment]
Updated storybook url.

**Comment by fernandolucchesi** [comment]
@padms LGTM!

**Comment by padms** [comment]
error page updated in radix
