### ISSUE TITLE
As a user I'd like the old Statoil news pages from 2016-2018 to be available as archived pages in the new solution

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#161]
Extract data from AEM

## Acceptance criteria
1. Live pages can be made static on demand
1. Pages available from Azure
1. Pages available from new site

## Sub-tasks
- [x] Create tool to extract content from AEM including assets
- [x] Figure out how to make pages available from new Sanity/Nextjs-based solution (implementation can wait)
- [x] Figure out how to do styling for the pages

**Comment by kalyanvaranasi** [comment]
@nilsml Refactoring script to extract the content of any page irrespective of its template.

**Comment by nilsml** [comment]
https://nextjs.org/blog/incremental-adoption

**Comment by kalyanvaranasi** [comment]
@nilsml I have gone through the article but I am not sure how it can solve our problem to handle header and footer from the new solution. My idea is to create a new archive component that takes the HTML content that is extracted from the AEM solution (ref the below draft image). Maybe we need to discuss with @wenche @SvSven 

![aem-archive-page (2)](https://user-images.githubusercontent.com/28557818/110608499-98915d00-818c-11eb-8dcf-a6b4eac87d6f.jpg)

**Comment by nilsml** [comment]
We should discuss this in the team @kalyanvaranasi

**Comment by kalyanvaranasi** [comment]
@nilsml Updated code to fetch page title and description and created local nextjs server and working on fetching the data and adding styles.

**Comment by kalyanvaranasi** [comment]
@nilsml I am able to display raw news pages in nextjs application and next steps are to

1. Remove Lazy load jQuery dependencies to the image components HTML
2. Clean up the styles and add only necessary styles. For this, I will create a new gulp task in AEM source code and generate archive-style.css file

**Comment by kalyanvaranasi** [comment]
@nilsml I have updated the web scrapper scripts to fetch all the client libraries required for the styles to work. We now have a working nextjs application that serves archived news.

We have to discuss when to integrate this with energy vision project

**Comment by kalyanvaranasi** [comment]
@nilsml I will start looking into old archive pages in AEM which should be moved to nextjs
