### ISSUE TITLE
Set up service account for running GH actions

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1758]
To stop using PAT for team members, a service account is needed.

## Sub-tasks
- [ ] Order Service Account from sdp team
- [ ] Add account with proper permissions to repositories
- [ ] Create PAT for the new account
- [ ] Replace PAT for all GH actions

## Acceptance criteria
* All PAT's used for envis belong to the service account
* All GH actions still work
* Team has a way to manage the service account. Password and other details needed are stored someplace safe.

**Comment by nilsml** [comment]
This is not possible atm, so we will have to go with PAT instead for now
