### ISSUE TITLE
As an editor I want all existing pages from AEM to be recreated in the new solution because they are still relevant

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#185]
Huge task!

## Acceptance criteria
1. The following pages need recreation: <TBD>

## In order to ensure good quality we should
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Perform user testing

**Comment by nilsml** [comment]
Ongoing task for the editorial team. Do we need to keep it here?

**Comment by nilsml** [comment]
Will close this epic as the dev team is not involved
