### ISSUE TITLE
As an editor I want a news article schema in Sanity so that I can create news articles

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#196]
## Acceptance criteria
1. A news schema is created
2. Input fields for title, publishing date, image (direct upload to Sanity in version 1), ingress, rich text editor
3. Validation rules according to Figma (min/max content, required fields)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Extra focus on usability
- [ ] Test for accessibility

## Sub tasks
- [x] #197 Create news schema with basic input fields
- [x] #199 Create a basic rich text editor
- [x] #200 Rich text editor: Add image
- [x] #201 Rich text editor: Add facts
- [x] #202 Add more on this topic

**Comment by wenche** [comment]
Should we not put #216 Horizontal divider in backlog for the time being? I think we agreed on that? If so, I think this US should be in review column

**Comment by nilsml** [comment]
I agree. The divider can be put in the backlog
