### ISSUE TITLE
As a team member I want to create building blocks for news article so that we make sure that good design and accessibility are in place

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#203]
## Acceptance criteria
1. All components for news article in the 1. version are created in Storybook

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for accessibility

## Sub tasks

- [x] #204 Create a quote component
- [x] #205 Create a fact box component
- [x] #206 Create "more on this topic" component
