### ISSUE TITLE
As a visitor on equinor.com I want to read news articles so that I can keep myself updated on relevant news

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#207]
## Acceptance criteria
1. A news article is available on a certain URI
2. The design looks good on small screen
...

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test

## Sub tasks

- [x] #208 (Create page /news/:id)
- [x] #209 (Add serializers for the rich text editor)
- [x] #210 (Image component)
- [x] #211 (Create a dummy /news)
