### ISSUE TITLE
As a team member I should be able to demo a stable version of Energy Vision

### ISSUE THREAD

**Issue by vnys** [equinor/energyvision#261]
## Tasks
- [ ] Create a `stable` environment in Radix
- [ ] Promote dev environment to stable in the Radix console once it’s stable
- [ ] Pin the URL of the environment in the Slack channel

## Acceptance criteria
1. The stable environment should be predictable and should not contain anything unsuspected nor should it break if there’s breakage in dev

## In order to ensure good quality we should
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform user testing

**Comment by nilsml** [comment]
Radix environment in place. Should we also have a stable Sanity environment?

**Comment by SvSven** [comment]
We can make another playground project and publish to that, but not sure if we can clone/share the dataset between that one and production. Might not be that bad if that one has a different dataset though?

**Comment by nilsml** [comment]
@nilsml to check if this is a duplicate
