### ISSUE TITLE
Create teaser component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#277]
**In order to promote and link to other pages, we will create a teaser component**

## Acceptance criteria
1. Add an image
1. Add an SVG file
1. Display a background colour 
1. Over line (eyebrow)
1. Title field
(1. Text field (Bold / Italic / hyperlink / Bullet / Numbers) ?? )
1. ACTIONS: links to internal or external pages.
1. ~~ACTIONS: Download files (EXE / PDF / JPG)~~ (version 2)
1. The teaser component itself is not clickable, the c2a performs the navigation
1. A c2a is mandatory in the Sanity studio 

## Sub-tasks (Create separate tasks for these)
- [x] Create teaser component in Storybook (#310)
- [x] Create teaser component for Sanity Studio  (#309)
- [x] Use the teaser component in the web page (#312)

## In order to ensure good quality we should
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
I guess you didn't want to close this @nicholas-haggerty?!

**Comment by nicholas-haggerty** [comment]
I blame the poor UI!

**Comment by wenche** [comment]
After some discussions, we will try to keep the scope for the teaser component as a two-column component with media content in one column and text with c2a in the other column.

The maximum height will be 800px.

The case with two-column text and c2a without media should be at Text component and not a teaser.

**Comment by wenche** [comment]
1. Display and play a video

Will be solved at a later point.

**Comment by wenche** [comment]
In the POC, the teaser component was a card with the fields (image/title/ingress) from the actual referenced content. This teaser component is _not_ that. This is a component where the publishers will add both the title and ingress and choose an image. 

We will need the other version as well, but let's try to use the terminology `"Card"` for that. (Internal link card or whatever)

**Comment by wenche** [comment]
We need to somehow split between SVG files and other images. We'll probably need two different image uploads, one with `.svg` and one for ordinary images.

**Comment by nilsml** [comment]
But handling SVG-files differently than other images would not be visible to the user, right? I mean we can detect the file type and do whatever we need to do.

**Comment by SvSven** [comment]
@nilsml It's mostly for the web part - there is a difference in design when using an SVG icon/illustration versus a picture, and we need to keep in mind that the SVGs may end up being animated at some point.

**Comment by nilsml** [comment]
Ok, sounds good @SvSven. Remember to add these requirements to the issue (or create a new one?) 😃

**Comment by wenche** [comment]
In a discussion last week, the following was suggested:

Add a theme/colour scheme/ variation selector in Sanity studio along with a highlight/emphasis text button in the rich text editor. Then the background colour and the colour of the highlighted text will be owned by the selected theme.

 Eg. Moss green background - default text colour with dark teal for highlighted text.

We need to find some clever naming for the theme/variation along with some icons in Sanity, and discuss this approach with Nick.

**Comment by nilsml** [comment]
Sounds good @wenche! Perhaps just set up a meeting with @nicholas-haggerty then to discuss this?!

**Comment by nicholas-haggerty** [comment]
Agree sounds good. Just let me know if/when you have time to go through. My afternoon is pretty meeting free!

**Comment by wenche** [comment]
@BirteThornquist  was in charge for this discussion, but I think she has EDS day today @nicholas-haggerty

**Comment by BirteThornquist** [comment]
Yes, today I'm working on EDS. We can meet tomorrow @nicholas-haggerty.

**Comment by wenche** [comment]
Let's just do a final review for the separate issues with Birte when she has her next Envis day, and then this will be ready for testing @nicholas-haggerty

**Comment by SvSven** [comment]
@nicholas-haggerty @petterwildhagen This should be ready for testing

**Comment by nicholas-haggerty** [comment]
- [ ] Add an image
- [ ] Add an SVG file
- [ ] Display a background colour
- [ ] Over line (eyebrow)
- [ ] Title field
- [ ] (1. Text field (Bold / Italic / hyperlink / Bullet / Numbers) ?? )
- [ ] ACTIONS: links to internal or external pages.
- [ ] The teaser component itself is not clickable, the c2a performs the navigation. A c2a is mandatory in the Sanity studio

Tested and approved by myself and Mette
