### ISSUE TITLE
Create text block component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#278]
**In order to show arbitrary text on a page, we will create a Text Block component**

## Acceptance criteria (to be determined)
1. It is possible to add a text block to a page in Sanity Studio
1. It is possible to edit the following fields for this component:

  a. Overline
  b. Subtitle (h2)
  c. Preamble
  d. Content 

Preamble and content need: Bold / Italic / Super & sub script / hyperlink / bullet / numbered / Left Center Right align / paste plain text

1. Component is displayed according to design in Figma on the web
1. Background styling options for colour as defined for teaser

## Sub-tasks
- [ ] Create text block component in Storybook
- [ ] Create component for Sanity Studio
- [ ] Add text block component to page schema
- [ ] Make component available to web/Next.js

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by wenche** [comment]
Moved from Teaser component

- Full width text
1. If no image selected, text displays to column grid (full width)

**Comment by wenche** [comment]
Text blocks should not  have an image.

Images (full width and preserve original dimensions) will be two separate components instead.

**Comment by wenche** [comment]
@nicholas-haggerty Birte and I just went through this. I have added the text block as a component in for the topic pages in Sanity (eyebrow, title, ingress and text along with the background color selector). I have also added some text components, you can visit https://energyvision.app.radix.equinor.com/careers if you'll like to see.

While you are able to test/verify that this works, @BirteThornquist  and I identified the need for some overall layout tweaks in the web and a tone of voice/naming/description task in Sanity to make things more consistent in the publishing interface. We will do this  when we have added all the components for v1 of the Topic pages. So expect some adjustments to the spacing in the web and in the Sanity interface. :)

**Comment by nicholas-haggerty** [comment]
@wenche Great. Looking good so far. And yup agree on the need for some spacing tweaks. Thanks for the update :)

**Comment by wenche** [comment]
(at)todo Remember to adjust the eyebrow on mobile

**Comment by wenche** [comment]
I guess this one should be ready for some sort of testing. At least we consider it as finished as it will be for this time. :) 

See [the Figma example](http://localhost:3000/careers/figma-example) as a start

**Comment by nilsml** [comment]
@petterwildhagen can you have a look at this?

**Comment by wenche** [comment]
@petterwildhagen  We have rearranged the page structure and moved things around, so the URL I pasted is deprecated. /careers will soon be OK

**Comment by petterwildhagen** [comment]
@BirteThornquist  Can you post link to Figma chart for this ? (Link above does not work)

**Comment by petterwildhagen** [comment]
Left Center Right align not implemented
paste plain text should not format text (text is currently formatted, i.e.  h3 content is formatted as h3 - should not be formatted).

**Comment by BirteThornquist** [comment]
@petterwildhagen [Here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1511%3A944) is the Figma link

**Comment by BirteThornquist** [comment]
@petterwildhagen there was a change regarding the button for text blocks. The button or CTA was at some point a separate page component but is now moved back into the text block.

**Comment by wenche** [comment]
@petterwildhagen 

- I don't know where this left| center | right requirement comes from, we haven't actually talked about this when we worked with the Text component. Is this something you think makes sense @BirteThornquist ?

**Comment by wenche** [comment]
Copy plain text doesn't actually makes sense either, because we don't actually want that. Image things like links, bold etc you want Sanity to respect that (and that's the way the Sanity editor works as well, they don't have a copy as plain text function as far as I know) 

But what we want to dig into at some point, is https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/226 which I created when we worked with the news articles. :)

**Comment by vnys** [comment]
> paste plain text should not format text

To paste plain text on the mac, you use **⇧⌘ V** – on Windows there’s a similar shortcut. So I don’t think we should spend time on replicating that functionality in Sanity.

**Comment by petterwildhagen** [comment]
[x] It is possible to add a text block to a page in Sanity Studio

It is possible to edit the following fields for this component:

a. Overline
b. Subtitle (h2)
c. Preamble
d. Content

Preamble and content need: Bold / Italic / Super & sub script / hyperlink / bullet / numbered / Left Center Right align / paste plain text

Component is displayed according to design in Figma on the web
Background styling options for colour as defined for teaser

**Comment by meols** [comment]
@SvSven @wenche @BirteThornquist 
I have tested on this page:
https://energyvision.app.radix.equinor.com/energy/buttons-and-links

- Spacing after bullet list item is wrong
- We will (almost) never want to keep formatting from word documents we receive. I have checked that ctrl+shift+v works (in Edge), and suggest that is added as help text, if it's not implemented in the component
- Can't find all pages to create internal link (e.g. Careers page when creating link on Buttons and links page)
- When browsing for internal links, title and url should be visible - not publishing date
- Doesn't seem to be able to edit the text with link (without removing the link, editing text and inserting link again)
- Can't drag or upload word file or zip file for download files
- Can't drag or upload jpg file or png file for download image
- Can't choose left-right-center aligned text

@petterwildhagen

**Comment by wenche** [comment]
`Spacing after bullet list item is wrong`
Yes, I can see that. But several issues here, also with the way <p> tags are used as header. We should revisit this when the component is more complete to see the whole picture. 

`We will (almost) never want to keep formatting from word documents we receive. I have checked that ctrl+shift+v works (in Edge), and suggest that is added as help text, if it's not implemented in the component`
I added this as a comment on the issue we have for this topic ([#226](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/226))

`Can't find all pages to create internal link (e.g. Careers page when creating link on Buttons and links page)`
We haven't actually fine tuned this as it's related to all the things we are working with now. I think it's only news for the time being. Will be fixed with the things we are working on now.
`When browsing for internal links, title and url should be visible - not publishing date`
I does show image and titles as well (and publishing date for the news). :)

![Skjermbilde 2021-06-11 kl. 08.43.06.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/199809ec-70ca-44f0-87cf-bb1d535c39d1)

`Doesn't seem to be able to edit the text with link (without removing the link, editing text and inserting link again)` It works for me with Chrome, I just click on the link, and the popover with edit options appears. If it doesn't work with your browser, it's actually a Sanity bug.

`Can't drag or upload word file or zip file for download files`
Word files has not been a requirement. We have a separate issue for investigation zip.
`Can't drag or upload jpg file or png file for download image`
This component shouldn't have image.
`Can't choose left-right-center aligned text`
This requirement has been removed (at least from this version)

`Alt texts on images should be optional, as we mostly use illustrative images. Code should only be alt=""`
I will create a separate issue for this. It easy to do technically, but we need to see how we can avoid mistakes with a11y if we make it optional, how should we explain this in the studio, how advanced is Axe for this and so on)

**Comment by nicholas-haggerty** [comment]
Based on the discussions/feedback provided and also the specific issues created as a result. I think we can close this issue. 

@meols we should discuss the need to L / C / R text as options with the rest of the editorial team. Im leaning towards no longer having that as option for consistency reasons.
