### ISSUE TITLE
Create "Array with text/icon" component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#279]
**In order to visually highlight key information, we will create an "Array of text/icon" component**

## Acceptance criteria
1. Component "Icon with text" is available in Sanity Studio for topic pages
1. Component is displayed according to Figma design on the web

## Sub-tasks
- [x] Create IconWithText component in Storybook
- [x] Create IconWithText component for Sanity Studio
- [x] Add IconWithText component to page schema

See POC for example

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by SvSven** [comment]
`TextWithIcon` is the main component and can be reviewed on [Storybook](https://envis-storybook.azureedge.net/?path=/docs/components-textwithicon--default)

`TextWithIconArray` is a group/array input in Sanity that allows the editors to add multiple `TextWithIcon` items grouped together.

###  Checklist for review:
- Should be able to select a background colour in Sanity
- Should be able to add multiple items
- The group of items is required in Sanity. If no items are added, a validation error is shown.

### Possible variations of the TextWithIcon:
- Just a title
- Just text
- Title + text
- Icon + title
- Icon + text
- Icon + title + text

### Validation:
An icon without title or text is not allowed
if an icon is selected but the title and text fields are empty, a validation error will show on the title and text fields.

**Comment by SvSven** [comment]
@BirteThornquist @petterwildhagen 

This is ready for review now

**Comment by SvSven** [comment]
Add guards for preview when creating content and no content has been added yet.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/089c5bbc-de0c-4add-a8e2-334712037a5e)

**Comment by nicholas-haggerty** [comment]
@wenche @SvSven 

1. We think none of the fields (title/text/ALT) should be mandatory, they should all be optional. So editors can in theory just add an icon with no title or text field.
2. If editor doesn't add ALT text in then default should be two hyphens in the code to indicate illustrative to screen readers.
3. Currently the icons do not arrange as per the POC (algorithmic design) Is this to be added now or at a later date? Is there an issue for this?

**Comment by wenche** [comment]
Issue with alt #369

**Comment by SvSven** [comment]
Issue for algorithmic design #393
