### ISSUE TITLE
Create button component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#281]
**In order to reach linked content on the careers page, we will create a button component**

## Acceptance criteria
1. Component should be able to handle both a single button and group multiple buttons together
1. Buttons can act as a link to internal and external page

## Known issues

1. The button colours does not work on coloured backgrounds. This is being handled by #363.

## Sub-tasks
- [ ] Create button group component in Storybook
- [ ] Make button component available to web
- [ ] Add button array to page schema

_Discovery: should buttons be able to link to downloadable content such as PDF, Excel, etc?_

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by SvSven** [comment]
Things to figure out:
- Do the EDS buttons cover all use cases here https://eds.equinor.com/components/buttons/
- Should we allow for different variations. If so, how?
- Should we have an option for both buttons with and without icons - if with, then how do we select the icon to use?
- Do buttons that are used as links (to internal or external pages) go against the design language/accessibility? (a button is a button, not a link)

**Comment by wenche** [comment]
If the publisher adds one link, display as a outline button (but still as an <a>)
If the publisher adds more than one link, display as content links

![Skjermbilde 2021-06-07 kl. 10.45.08.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/adc20787-36af-4327-b9eb-06581d3f4b78)![Skjermbilde 2021-06-07 kl. 10.45.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a53f6418-e076-4695-8588-520b3c364426)

**Comment by wenche** [comment]
We decided to add the c2a to the text block component.

**Comment by wenche** [comment]
@nilsml @BirteThornquist  What do you think, should we do all the work related to the use of the EDS button on coloured backgrounds as a part of this task or create a separate one? 

We'll probably need (at least)

- Better contrasts, Birte has suggested to use a white background on the button for Envis
- Another hover colour as the baby blue from EDS looks strange on e.g. spruce wood ![Skjermbilde 2021-06-07 kl. 15.40.13.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/23319400-641b-4fe7-b45e-0785eb2582c7)

**Comment by wenche** [comment]
Ready for testing / verification @petterwildhagen  As mentioned, this is no longer a separate component in the content list, but one field in the text block component.

The idea we are testing is to render one c2a as a outlined EDS button and > 1 as a list of content links like we do in related content. Se /careers/figma-example for some examples.

![Skjermbilde 2021-06-07 kl. 14.29.55.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c1b013fa-4029-4a83-82ed-a3532cbf293f)![Skjermbilde 2021-06-07 kl. 14.29.47.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9a145444-888b-4945-833c-1b4fc4f4d3c2)

**Comment by meols** [comment]
- [ ] Component should be able to handle both a single button and group multiple buttons together
- [ ] Buttons can act as a link to internal and external page

@SvSven @BirteThornquist @wenche 

We are able to add both a single button and multiple buttons - but nothing is visible in the preview or published page
Internal/external links are added, but not tested du to the above
Question: could the component have an optional title, ore should we add a textcomponent with one word for e.g. Downloads etc, see e.g. this page with buttons: https://www.equinor.com/en/investors/quarterly-results.html

@petterwildhagen

**Comment by wenche** [comment]
@meols 

I can see in the Studio that the links you have added are created by using the first variant of the buttons, before we decided to move this into the Text block component. (And this was obviously still available when you started to test because of the issues with the production environment :/ )

So to test this, you should add links with the Text block component![Skjermbilde 2021-06-11 kl. 08.16.44.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/91e86852-a55d-489a-99d1-e9a83b9f9120)

I have created several on https://energyvision.app.radix.equinor.com/careers

`Question: could the component have an optional title, ore should we add a textcomponent with one word for e.g.` We haven't actually discussed this, we have titles for the related content component in the News articles, but in this case it's already inside a text block. But one of those things we can easily tune later when more content is added. 

`Downloads etc, see e.g. this page with buttons: https://www.equinor.com/en/investors/quarterly-results.html` I don't think this example has been taken into consideration at this point by Birte, I would say we can look at this while we are creating more components, and probably solve it in a better way. :)
