### ISSUE TITLE
In order to get a picture on what will be delivered at what time, we will define milestones for the project

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#302]
## Sub-Tasks
- [x] Define Epics for the project - an epic should not take more than a month to complete
- [ ] Put Epics into milestones and updated roadmap
- [ ] Given our current velocity; find out how much we can produce in the near future

**Comment by nilsml** [comment]
Themes and epics created. Now the team needs to participate in defining reasonable milestones.

**Comment by nilsml** [comment]
Further involvement from the team needed here. Nick to work with Birte on setting up a preliminary plan for the project. Developers to give input on technical tasks and where they may fit within this plan.

### Questions for the first two milestones:

1. Localization is something we should plan for quite soon. What parts of the localization should we do in a first iteration?
1. What is needed in order to serve static pages from new solution? Do we need to do some work on the menu f.ex. in order to achieve that?
1. When do we think it makes sense to have something live? Hence; when to have a production system ready?

**Comment by nicholas-haggerty** [comment]
@nilsml  @BirteThornquist and I have created added tasks to the next two epics . #270 Topic page version 2 & #271 Topic page version 3. This is based on what we feel make sense to work on from a component perspective, and also includes tasks relating to other epics. This is just a suggestion so can and will shift based on what makes sense from the developers pov. Obviously the developers may see the need to define these tasks into iterations too, so these iterations need to be carried forward to the next milestone if they are not completed in the designated milestone.
