### ISSUE TITLE
In order to have a working production environment, we need to find out where to run the application

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#304]
## Acceptance criteria
1. Production environment has an SLA that fits the project needs
1. Proper (to be defined) monitoring in place
1. Access to logs for application
1. Scales to the needs of this project

## Sub-tasks
- [x] Set up architecture contract meeting and discuss options
- [x] Find approximate price for Vercel
- [x] Outline the requirements we have for a production environment
- [ ] Prepare a document showing the cost benefits by using Vercel (if any)
- [ ] If Vercel seem to be the better option, add tasks for further work (assesment, procurement, etc)

**Comment by nilsml** [comment]
We have something running in both Vercel and Radix now. Let's evaluate which one. If Vercel is technically much better, we can continue setting up a cost/benefit document.

**Comment by nilsml** [comment]
## Requirements for production environment
1. Easy to deploy
2. Easy to scale
3. Monitoring capabilities
4. Good™ Performance*
5. Acceptable Uptime**

### *Performance
We don't have defined metrics for performance yet. This will be worked on when solution is more complete.
For now performance has been measured by comparing Vercel to Radix. 

### *Uptime
Solutions compared by looking at actual uptime, not the SLA.

## Comparison between the two solutions
|Requirement|Radix|Vercel|
|---|---|---|
|Easy to deploy|When using GH for building and Radix only for deploying, it seems to be working quite well|Equally easy to deploy. Has it's own CLI and handle all the building itself|
|Easy to scale|Radix is using Kubernetes which is made for scaling|Vercel is handling this. Not 100% sure how though|
|Monitoring capabilities|Prometheus and Grafana available. Also logging to Azure Insights.|More analytics out of the box. It seems like advanced monitoring and logging is something one would need do ourselves|
|Good performance|
|Acceptable uptime|





For now we have **not** done any extensive performance testing, but simple tests shows similar response times as Vercel. Need to test this more extensively when solution is more complete.

**Comment by nilsml** [comment]
Any other parameter we should compare for these two hosting platforms @SvSven @wenche?

**Comment by nilsml** [comment]
Will leave this as is for now. Let's do a new round of comparison once we have more to test.
To be continued...
