### ISSUE TITLE
As an editor I want to be able to promote multiple in a minimal list/card component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#562]
Minimal Card (title TBC!)
Simple card component that could be used on certain pages eg ENERGY or ABOUT us. That serves more as a table of contents display than offering information upfront.

Card displays:
Image from reference page
Title from reference page
Card automatically displays pages that are build under the 'SECTION' eg ENERGY.
Whole card is clickable and takes user to the referenced page. 

## TODO
- [x] Create a landing page template
- [x]  Select the landing page as a top level route
- [x]  Create a the template in the web
- [x]  Find a way to populate the landing page with the corresponding content from the relevant menu item
- [x]  Create a simple version of the card
- [x] What can we do for preview

**Comment by wenche** [comment]
First, we need to figure out how we can populate the landing page with the related sub pages from the menu

**Comment by wenche** [comment]
@nicholas-haggerty  This is the current status https://energyvision.app.radix.equinor.com/about-us While this technically work (it does list the sub menu items from the corresponding top level menu item) it's pretty fragile. What we do is to verify that the menu has a reference for this landing page (about-us in this case) and then we choose the sub menu data for the sub menu that has the top level link with the same slug as the landing page.

I think this would be more robust if we instead add a reference on the landing page itself to the actual sub menu document. With this workflow, the link between the landing page and the data would be a lot more safe and explicit, you'll have more warnings if you delete a sub menu with a corresponding landing page and the query itself in the web would be a lot safer. But since Sanity has a release to improve the whole workflow here, I think we should wait for that?  They say that it should be "very soon"

**Comment by wenche** [comment]
I created issue #593 to see if we can improve the data fetching with the new soon-to-be-released features from Sanity

**Comment by wenche** [comment]
Preview for the routes work like the topic page based content. Let's see if we can make the landing page template preview work as well with query by id as we do for the topic

**Comment by wenche** [comment]
We see the same issue for the preview of the landing page template as we did for news during the sanity user test: The preview doesn't work before the document is initially published. I have updated #401 and we should prioritise this.

When the document is published, preview works in the same way as for the landing pages even if it's not yet connected to a route.

**Comment by wenche** [comment]
1. Added a new landing page template and corresponding menu item
![Skjermbilde 2021-11-17 kl. 12.35.46.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/0b412c77-c17c-41f3-9b05-a8147592866d)
![Skjermbilde 2021-11-17 kl. 12.36.25.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/5a743c3e-f21b-4c42-afb3-e2c0251be39f)
2. A page of type landing page can be selected as the content in the Topic Route
(With one limitation: It can also be selected as the content for a child route (one with a parent) I'm not sure how much time we should spend on improving this (if possible)
3 In the web, it will fetch the corresponding sub menu and display the menu items as simple cards

**Comment by wenche** [comment]
@nicholas-haggerty please take a look

**Comment by nicholas-haggerty** [comment]
@wenche Fantastic work! Looks good. Made some changes to the About us Menu. Works like a dream on the landing page view. I guess the issue we will have to live with is the lack of preview image on the static page references, but as tested, works great on a dynamic page.

Agree, lets wait for the workflow fix from Sanity

Just want to confirm that this 'table of content' is only for certain landing pages. ENERGY (when it comes) ABOUT US, WHERE WE ARE. Some landing pages will feature the standard template content. How do editors setup the difference behaviour?

**Comment by wenche** [comment]
> Just want to confirm that this 'table of content' is only for certain landing pages. ENERGY (when it comes) ABOUT US, WHERE WE ARE. Some landing pages will feature the standard template content. How do editors setup the difference behaviour?

The editors could still choose a topic page as the content for a landing page in Sanity -> Topic Route :)

**Comment by nicholas-haggerty** [comment]
Ok, still not quite understanding the logic (or rather, why does one section display one way (ToC) and one section another way (Topic page) but lets have a walk through at some point.

**Comment by wenche** [comment]
It is because the web are able to figure out which kind of content the routes references and use the Topic page template or the landing page template accordingly

**Comment by nicholas-haggerty** [comment]
Ok so the editor workflow is.... If an editor adds the page to 'landing page' route its ToC view. If the page is set up as a topic and referenced from the menu route, its displayed as a Topic page. Guess I was confused because we have Careers in the landing page part too..... 
Well Im still a little confused with the whole topic page vs route vs menu vs slugs vs content vs landing page thing tbh!
