### ISSUE TITLE
Improve the News card

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#572]
### Todo

- [x]  Revisit the use of the EDS card
- [x] Add the new design (shadows and more)
- [x] See if the images are still performant

### Acceptance criteria
- News card looks like the design in Figma

**Comment by wenche** [comment]
@BirteThornquist  or @nicholas-haggerty According to Figma, the 4px rounded corners from EDS are gone?

**Comment by nicholas-haggerty** [comment]
@wenche I don't have a super strong opinion on this visually. Not sure of the impact if we are changing the EDS card set up? We had already gone without the rounded corners on the news feed/promo at the bottom of each news article. But if its less complicated to have the corners, then as long as its consistent, Im ok with them in place.

**Comment by wenche** [comment]
![Skjermbilde 2021-11-03 kl. 15.43.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ec225d94-6972-4239-acba-329c70611461)

@nicholas-haggerty It's actually more complicated with the rounded corners. So I want spend time on reintroducing them, I think it looks good like this

**Comment by nicholas-haggerty** [comment]
Lets not have them then. I think the above looks excellenteeeeeeeee

**Comment by wenche** [comment]
@BirteThornquist  Let's take the final adjustments when you are back
