### ISSUE TITLE
As a editor I want to add a simple menu to satellite pages

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#675]
## Acceptance criteria
1. Satellite sites should have a simple menu in Studio instead of normal
2. Web application should render simple menu instead of normal in satellites

## Steps to produce
1. Create a menu in Sanity for a satellite site. 
2. See if it renders on the satellite site

## Todo: 
- [x] Logo in header
- [x] Remove static links in satellite
- [x] Add link field at root

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability

- [ ] Test for accessibility

- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nicholas-haggerty** [comment]
@BirteThornquist Lets discuss the simple menu design this week too

**Comment by adneforslund** [comment]
@nicholas-haggerty @meols ready to add content now

**Comment by adneforslund** [comment]
https://web-brazil-energyvision-dev.radix.equinor.com/

**Comment by fernandolucchesi** [comment]
The css on desktop view is broken when the text is too long. Item is placed inside a grid that limits its width:
![image](https://user-images.githubusercontent.com/23337266/150338728-f01e8570-138f-413d-9066-959c6ad2a647.png)

Due to this, on my screen resolution a line break is being introduced when hovering the item:
![image](https://user-images.githubusercontent.com/23337266/150338857-66ea1137-bbde-49fb-a3ed-bd5cdafcf133.png)
![image](https://user-images.githubusercontent.com/23337266/150338882-842f6526-7057-451f-af33-a6cf8ed08e9d.png)

There is also a mismatch on the position of the `Menu` button when the menu is opened vs closed. This is also happening for the global menu and I believe this can be considered a case of [Cumulative Layout Shift](https://web.dev/cls/?gclid=Cj0KCQiAraSPBhDuARIsAM3Js4rNFI6K9uW88qSp2QbFAQFrpVnRe4acloT_RmfO_F-tiX6kTsBdkMYaAjmqEALw_wcB). So I'd suggested we fix this too, for both menus. What do you think @BirteThornquist ?

**Comment by SvSven** [comment]
We had issues with the menu button placement before, it's because of a number of things (scrollbars and offset for that amongst which) but it boils down to that we use 2 different buttons; one for when the menu is closed and one for when the menu is open.

It's been tinkered with several times before. If it keeps messing up and we want to properly fix it, we should look into just using a single button that is positioned absolutely or something.

**Comment by wenche** [comment]
@SvSven #789 was created to solve that. It was due to the language switch

**Comment by wenche** [comment]
And btw @adneforslund  when you moved some styles according to Fernando's input, the storybook example for the menu broke as well.

**Comment by SvSven** [comment]
We had a walkthrough about this on Friday and at least the Sanity part and the design looks good 👍

**Comment by nilsml** [comment]
Storybook implementation needs to be looked at as it does not work for desktop now.

**Comment by adneforslund** [comment]
https://github.com/equinor/energyvision/commit/338e6bf4ccf1c83b4ef0445332fd008e3eebdd16 is the commit that broke Storybook

**Comment by adneforslund** [comment]
@wenche help

**Comment by nilsml** [comment]
In review. Being looked at by me and @wenche
