### ISSUE TITLE
Make plan for environments in Radix

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#828]
## Todo

- [x] Architecture needs to be sketched out
- [x] Figure out how to do without dev dataset for satellites and how to enable promotion of dev->prod
- [x] Create new stories for actually implementing this
- [x] Point to stage version of archived pages for test environment

**Comment by nilsml** [comment]
Working on architecture for the deployment setup:
https://www.figma.com/file/pNan4g7GgZEoRpqSUKdURl/Environments?node-id=0%3A1

**Comment by wenche** [comment]
@nilsml  To update the drawing
