### ISSUE TITLE
As a user I want to view the content of Equinor's sites in my native language so that I understand it

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#93]
## Acceptance criteria
1. Supported languages
    * Norwegian
    * English
1. It is possible for the user to select language
1. The content should be shown in the language suggested by browser settings if possible
    * Default to English if browser language not supported
    * Language selected by the user trumps browser settings

## Sub-tasks:
- [ ] Add button for selecting language #96
- [ ] Store language selection in the browser
- [ ] Honour stored language when loading site

## In order to ensure good quality we should:
- [ ] Have extra focus on intuitiveness
- [ ] Test functionality in multiple browsers
- [ ] User testing to ensure the solution is intuitive
- [ ] Enable smoke tests to prevent regressions
