### ISSUE TITLE
Prepare Storage for going live

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#968]
## Sub-tasks
- [x] Add ticket for DNS
- [x] Add external alias to radixconfig
- [x] Add certificate to radix
- [x] Add sitemap.xml
- [x] Add GTM config

**Comment by nilsml** [comment]
@fernandolucchesi I guess we/you need to configure GTM for storage?

**Comment by fernandolucchesi** [comment]
https://github.com/equinor/energyvision-internal/commit/7f3af605e8a0a192ce564681e2a2da8fc3609647

**Comment by nilsml** [comment]
We are live!
